[bot]
channel = "@chumkassa"
subscribe_guard = true

start = '''
Салам, {name} {last_name}
Толтур/чыгар акча  1X тен!

📥толтуруу: 0%
📤чынаруу: 0%
👨‍💻Работаем 24/7

👨‍💻Служба поддержки: @zero1win
💕Kанал : @chumkassa
🔐Ваши транзакции Защищены Финансовой службой 1X!
'''

start_buttons = [
    "ПОПОЛНЕНИЕ", 
    "ВЫВОД",
    "Инструкция",
    "Перевести на кыргызский"
]
