[bot]
channel = "@chumkassa"
subscribe_guard = true

start = '''
Салам, {name} {last_name}
Толтур/чыгар акча  1X тен!

📥толтуруу: 0%
📤чыгаруу: 0%
👨‍💻 24/7 бою иштейбиз

👨‍💻Служба поддержки: @zero1win
💕Kанал : @chumkassa
🔐Сиздин транзакция  1X кызматы менен битта корголгон!
'''

start_buttons = [
    "Толтуруу", 
    "Чыгаруу",
    "Инструкция",
    "Орусча котор"
]

replenish_message= '''
    Зайбал танда!
'''
replenish_buttons = [
    'MBANK',
    'OptimaBank'
]

withdraw_buttons = [
    'MBANK',
    'OptimaBank'
]
withdraw_message = '''
    акчаны кайсы банкка чыгарасыз?, 
'''
withdraw_option = '''
Тандалган банк: {bank}
'''
withdraw_request_bank_id = '''
     Кошелек номерин жазыныз 
'''
withdraw_request_bank_phone = '''
    Введите номер телефона счета {bank}
'''
withdraw_conditions = '''
Условия для вывода средств: 
Вывод доступен только тем пользователям которые пополняли через нашего бота.
Если вы пололняли через другую платформу вывод не будет отправлен

Спасибо за понимание!
'''

report_withdraw = '''
Сиздин заявка кабыл алынды :
Маалымат натыйжа.
Банк : {bank}
Имя: {name}
ИксБет : {xid}
Сумма : {price}

Вам придет оповешение когда выведим средства!

'''


flood_message = 'Жон дейм!' 

handle_xid = 'Введите xbet ID !' 
invalid_xid = 'Вы отправили неправильный xbet id , Пожалуйста проверьте ваг xbet id!' 

handle_price = 'Введите сумму в райное 3000 и 10000 сомов!' 
invalid_price = 'Не правильная цена , Введите сумму в райное 3000 и 10000 сомов!' 

check_photo = "Отправьте фото чека"
chosen_method = '''
Выбран метод оплаты: {method} 
Введите ФИО {method} аккаунта
'''

pay_info = '''
толой турган акча: {price}
Реквизиттер: 996776512096
Бассан скопировать болот

Отправьте указанную сумму на счет и ОТПРАВЬТЕ ЧЕК
❗ Pdf и дургие форматы не принимаются
❗ Только чек лист скриншот экрана
'''

report_payment = '''
Сиздин заявка кабыл алынды :
маалымат
Банк : {bank}
Аты жону: {name}
ИксБет : {xid}
Топтом : {price}

Вам придет оповешение когда будет пополнение счета
'''

misunderstanding = '''
    Мен сизди такыр эле тушунбой жатам,  /start басып корунуз
'''

instructions = '''
Кандай жардам керек ?
'''

cancel="Отменитет"

oops = "Ой что то пошло не так, скоро мы это починим."